---
title: "Inferential Statistics"
author: ""
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE,
    warning = FALSE
)
```

```{r, results='hide', warning=FALSE, message=FALSE, attr.source='.numberLines'}
library(ggplot2)
library(readxl)
library(tidyverse)
```

```{r, results='hide', warning=FALSE, message=FALSE, attr.source='.numberLines'}
df <- read_xlsx(
    path = "17-Influence of Webinars and Seminars on Students’ Academic Performance.xlsx"
)
```

------------------------------------------------------------------------

### **Hypotheses:**

-   **Null Hypothesis (H0):** The mean perceptions of the impact of webinar and seminar attendance on academic performance are the same among participants.

-   **Alternative Hypothesis (H1):** There is a significant difference in the mean perceptions of the impact of webinar and seminar attendance on academic performance among participants.

> Type of T-Test: This scenario corresponds to an Independent Two-Sample T-Test.

```{r, results='hide', warning=FALSE, message=FALSE, attr.source='.numberLines'}
graduates <- df[
    df$`What is your current level of education?`
    %in%
    c(
        "Undergraduate (Bachelor's degree)",
        "Graduate (Master's or higher)"
    ),
]

graduates$Attendance <- as.numeric(
    factor(
        x = graduates$`Do you attend webinars and seminars related to your study?`,
        levels = c(
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree"
        )
    )
)

t_test_result <- t.test(
    formula = Attendance ~ `What is your current level of education?`,
    var.eqaul = TRUE,
    data = graduates
)
```

### **Conclusion:**

-   **p-value (0.08349) \> 0.05:** This suggests that there is not enough evidence to reject the null hypothesis.

-   **Confidence Interval:** At 95% confidence interval, there is no significant difference in the mean perceptions of attendance between Graduate and Undergraduate participants.

------------------------------------------------------------------------

### **Hypotheses:**

-   **Null Hypothesis (H0):** The means of responses to the accessibility of webinars are equal across different educational levels.

-   **Alternative Hypothesis (H1):** At least one group mean of responses to the accessibility of webinars is different from the others.

> Type of ANOVA Test: This scenario corresponds to a one-way ANOVA.

```{r, results='hide', warning=FALSE, message=FALSE, attr.source='.numberLines'}
graduates <- df[
    df$`What is your current level of education?`
    %in%
    c(
        "High School",
        "Undergraduate (Bachelor's degree)",
        "Graduate (Master's or higher)",
        "Others (please specify)"
    ),
]


graduates$Accessibility <- as.numeric(
    factor(
        x = graduates$`Preferences [Webinars are more accessible to a wider audience compared to seminars.]`,
        levels = c(
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree"
        )
    )
)

t_test_result <- aov(
    formula = Accessibility ~ `What is your current level of education?`,
    data = graduates,
)

summary(graduates)
```
