---
title: "Influence of Webinars and Seminars on Students’ Academic Performance"
subtitle: "Descriptive Statistics"
author: "Bivas Kumar (2347111)"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r}
# load the required libraries
# ggplot is for plotting
# dplyr is for easy data frame manipulation
# readxl for working with Microsoft Excel file
library(ggplot2)
library(dplyr)
library(readxl)

# read the *.xlsx file that has the survey responses
dataset <- read_xlsx(
    path = "/home/bivas/dev/mca/2/asr/assignment/17-Influence of Webinars and Seminars on Students’ Academic Performance.xlsx"
)

demographic_dataset = select(
    dataset,
    "What is your current level of education?",
    "Do you attend webinars and seminars related to your study?",
    "Have you participated in both seminars and webinars for educational purposes?",
    "Do you use online learning resources, such as webinars, in your education?",
    "How many hours per week do you spend on online learning activities, including webinars and seminars?"
)

# drop NA values
demographic_dataset <- na.omit(demographic_dataset)

summary(demographic_dataset)
```

```{r}
Education <- demographic_dataset$`What is your current level of education?`

ggplot(
    demographic_dataset,
    aes(
        x = Education,
        y = Education,
        fill = Education)
    ) +
    geom_bar(width = .5, stat = "identity") +
    labs(title = "Education Level Distribution", x = "", y = "") +
    coord_polar("y", start = 0)
```

```{r}
Attendace <- demographic_dataset$`Do you attend webinars and seminars related to your study?`

ggplot(
    demographic_dataset,
    aes(
        x = Attendace,
        y = Attendace,
        fill = Attendace,)
    ) +
    geom_bar(width = .5, stat = "identity") +
    labs(title = "Education Level Distribution", x = "", y = "") +
    coord_polar("y", start = 0)
```

```{r}
Participation <- factor(demographic_dataset$`Have you participated in both seminars and webinars for educational purposes?`)

ggplot(
    data = demographic_dataset,
    aes(
        x = Participation,
        y = Participation,
        fill = Participation)
    ) +
    geom_bar(width = .5, position = "fill", stat = "identity") +
    labs(title = "Participation in Webinars & Seminars", x = "", y = "") +
    coord_polar("y", start = 0)
```

```{r}
Usage <- factor(
    demographic_dataset$`Do you use online learning resources, such as webinars, in your education?`
)

ggplot(
    data = demographic_dataset,
    aes(x = "", fill = Usage)) +
    geom_bar(width = 1, position = "fill") +
    coord_polar(theta = "y") +
    labs(title = "Use of Online Learning Resources", x="")
```
